/*jslint node: true, nomen: true */
"use strict";

var ko = require('knockout');

exports.register = function () {
    require('./main-application').register();
    require('./c-croudsourcecontainer').register();
    require('./c-croudsourceviewcontainer').register();
    require('./c-indexpage').register();
    require('./c-app').register();
    require('./c-registeruserfrom').register();
    require('./c-loginuserform').register();
    require('./c-appcontainer').register();
    require('./c-homepagemanager').register();
    require('./c-profilecontainer').register();
    require('./c-workerhomecontainer').register();
    require('./c-managerhomecontainer').register();
    require('./c-profileview').register();
    require('./c-workerhomecontainerview').register();
    require('./c-campaignlistcontainer').register();
    require('./c-createcampaignmodel').register();
    require('./c-runningcampaigncontainer').register();
    require('./c-completedcampaigndetails').register();
    require('./c-unpublishedcampaigndetails').register();
    require('./c-fullnamechangecontainer').register();
    require('./c-changepasswordcontainer').register();
    require('./c-userdetails').register();
    require('./c-selectiontaskview').register();
    require('./c-usertaskscontainer').register();
    require('./c-annotationtaskview').register();
    require('./c-createcampaignform').register();
    require('./c-runningcampaignview').register();
    require('./c-detailscompleted').register();
    require('./c-campaigncontainer').register();
    require('./c-changenameform').register();
    require('./c-changepasswordform').register();
    require('./c-userpersonaldetails').register();
    require('./c-imageselectiontask').register();
    require('./c-tasktypefilter').register();
    require('./c-taskstatistics').register();
    require('./c-annotationtask').register();
    require('./c-campaignlistcontainerrunning').register();
    require('./c-annotationscontainer').register();
    require('./c-modifycampaignformcontainer').register();
    require('./c-imageslistcontainer').register();
    require('./c-imageuploadcontainer').register();
    require('./c-selectworkerscontainer').register();
    require('./c-runningcampaignimagelist').register();
    require('./c-imagestatisticsrunning').register();
    require('./c-annotationslist').register();
    require('./c-modifycampaignform').register();
    require('./c-campagnimageslist').register();
    require('./c-campaignimagedetails').register();
    require('./c-imageuploadform').register();
    require('./c-executionstatelist').register();
    require('./c-campaignlist').register();
    require('./c-tasktypelist').register();
    require('./c-campaignworkeslist').register();
    require('./c-taskslist').register();
};
